apiVersion: batch/v1
kind: CronJob
metadata:
  name: ilogs-backup-s3
  namespace: utils
spec:
  schedule: "0 0 * * 0"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: ilogs-backup-s3
    spec:
      template:
        metadata: {}
        spec:
          containers:
            - image: registry.digitalocean.com/munyaal-docr/pg-backup-agent:86d823c
              name: ilogs-backup-s3
              envFrom:
                - secretRef:
                    name: aws-backup-secret
                - secretRef:
                    name: ilogs-datasource-secret
              resources: {}
          restartPolicy: OnFailure
